name: Everest Balnea - Qualidade Total
on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do Código
              uses: actions/checkout@v4

            - name: Instalar Dependências e Rodar Cypress
              uses: cypress-io/github-action@v6
              with:
               # Inicia um servidor estático leve na porta 5500 igual ao seu Live Server
                start:start: npx serve frontend -p 5500
                wait-on: 'http://localhost:5500'